.TH PIPEWRENCH 1 "Sep 2014"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
PipeWrench \- transform text into other forms using stackable filters
.SH SYNOPSIS
.B pipewrench 
.SH DESCRIPTION
.B PipeWrench
is a high-level text scripting tool that allows you to easily
transform text, (i.e. lists, command output, HTML, config files, log
files, source code, CSV data, etc.) from one form to another with
relative ease. In a PipeWrench script, there's no need to create
conditional or looping constructs or even to declare variables. You
simply "stack" filters to get the results you want. And when you're
done building your "pipe script" using PipeWrench's editor, you can 
export it for use at the command line.

.PP
For more detailed documentation, see the PipeWrench user guide.
.SH NOTES
.B PipeWrench
is limited to working with just the amount of text that it can hold 
in memory at one time and it isn't intended for use in applications 
that require handling of more text than will fit in memory.  If you 
require such capability you might want to consider other available
solutions. 
.SH SEE ALSO
.BR pcl (1)
.BR awk (1)
.BR sed (1)
.SH AUTHOR
Barry Block
